server:
  port: 8001

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000
logging:
  level:
    cn.liulingfengyu.oauthresourceserver: debug  #日志级别