server:
  port: 9000

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/unified_certification?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1q@w3e4r
    hikari:
      pool-name: HikariCP
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      connection-timeout: 30000
      connection-test-query: SELECT 1
      max-lifetime: 25200000
logging:
  level:
    root: info
    org.springframework.web: info
    org.springframework.security: info
    org.springframework.security.oauth2: info